CONFIG:
  IA_PS1:
    BASE: /project2/rkessler/SURVEYS/PS1MD/USERS/dscolnic/PANTHEON+/siminputs/SIMGEN_MASTER_SDSS_data.INPUT
    GENPEAK_SALT2BETA: 2.0
    GENSIGMA_SALT2BETA: .35 .35
    GENRANGE_SALT2BETA: .4 13
    GENGRID_SALT2BETA: 0
    GENMAG_SMEAR: 1.0e-06
    HOSTLIB_FILE: $PANTHEONPLUS/HOSTLIBS/F2/HIZ-SPEC-BS20.HOSTLIB
    GENPEAK_SALT2ALPHA: 0.145
    GENPEAK_SALT2c: -0.084
    GENSIGMA_SALT2c: 0.042  0.042
    GENRANGE_SALT2c: -0.40    0.50
    HOSTLIB_SCALE_LOGMASS_ERR: 0.0
    GENMAG_SMEAR_MODELNAME: C11
    GENMAG_SMEAR_SCALE: 0.0001
    GENMAG_SMEAR_SCALE(c): 0,0
    GENPDF_FILE: /project2/rkessler/SURVEYS/SDSS/USERS/BAP37/MASS_paper/AS/DISTS/HIGHZ_lowRVSTD.v2.DAT
    GENMAG_OFF_GLOBAL: -0.12
    HOSTLIB_MSKOPT: 66
    GENMODEL: $PANTHEONPLUS/submit_trainSALT2/out_train_v6_1/SALT2.MODEL000
    OPT_MWCOLORLAW: 89
    OPT_MWEBV: 3
    GENSIGMA_VPEC: 0
    VPEC_ERR: 0
    SEARCHEFF_SPEC_FILE: $SDSS_USERS/BAP37/MASS_paper/AS/DISTS/SDSS_SPECEFF.DAT
    HOSTLIB_WGTMAP_FILE: $PANTHEONPLUS/siminputs/SDSS.v2.WGT
  GLOBAL:
    NGEN_UNIT: 0.8
    FORMAT_MASK: 48
    RESET_CIDOFF: 2
    RANSEED_CHANGE: 10 12346
    BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2b.TEMPLATE 10
  GENVERSION: PIP_PLUS_10REAL_SIMSDSSREAL_4D_BS20
OUTPUT:
  name: SIMSDSSREAL_4D_BS20
  output_dir: /scratch/midway2/rkessler/PIPPIN_OUTPUT/PLUS_10REAL/1_SIM/SIMSDSSREAL_4D_BS20
  hash_file: /scratch/midway2/rkessler/PIPPIN_OUTPUT/PLUS_10REAL/1_SIM/SIMSDSSREAL_4D_BS20/hash.txt
  done_file: /scratch/midway2/rkessler/PIPPIN_OUTPUT/PLUS_10REAL/1_SIM/SIMSDSSREAL_4D_BS20/done.txt
  types_dict:
    IA:
    - 1
    - 101
    NONIA: []
  types:
    1: Ia
    101: Ia
  blind: false
  genversion: PIP_PLUS_10REAL_SIMSDSSREAL_4D_BS20
  genprefix: PIP_PLUS_10REAL_SIMSDSSRE959a4
  ranseed_change: true
  ranseed_change_val: 10 12346
  sim_folders:
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_PLUS_10REAL_SIMSDSSREAL_4D_BS20-0001
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_PLUS_10REAL_SIMSDSSREAL_4D_BS20-0002
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_PLUS_10REAL_SIMSDSSREAL_4D_BS20-0003
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_PLUS_10REAL_SIMSDSSREAL_4D_BS20-0004
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_PLUS_10REAL_SIMSDSSREAL_4D_BS20-0005
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_PLUS_10REAL_SIMSDSSREAL_4D_BS20-0006
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_PLUS_10REAL_SIMSDSSREAL_4D_BS20-0007
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_PLUS_10REAL_SIMSDSSREAL_4D_BS20-0008
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_PLUS_10REAL_SIMSDSSREAL_4D_BS20-0009
  - /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_PLUS_10REAL_SIMSDSSREAL_4D_BS20-0010
  SURVEY: SDSS
  SURVEY_ID: 1
  photometry_dirs:
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/PLUS_10REAL/1_SIM/SIMSDSSREAL_4D_BS20/PIP_PLUS_10REAL_SIMSDSSREAL_4D_BS20-0001
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/PLUS_10REAL/1_SIM/SIMSDSSREAL_4D_BS20/PIP_PLUS_10REAL_SIMSDSSREAL_4D_BS20-0002
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/PLUS_10REAL/1_SIM/SIMSDSSREAL_4D_BS20/PIP_PLUS_10REAL_SIMSDSSREAL_4D_BS20-0003
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/PLUS_10REAL/1_SIM/SIMSDSSREAL_4D_BS20/PIP_PLUS_10REAL_SIMSDSSREAL_4D_BS20-0004
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/PLUS_10REAL/1_SIM/SIMSDSSREAL_4D_BS20/PIP_PLUS_10REAL_SIMSDSSREAL_4D_BS20-0005
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/PLUS_10REAL/1_SIM/SIMSDSSREAL_4D_BS20/PIP_PLUS_10REAL_SIMSDSSREAL_4D_BS20-0006
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/PLUS_10REAL/1_SIM/SIMSDSSREAL_4D_BS20/PIP_PLUS_10REAL_SIMSDSSREAL_4D_BS20-0007
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/PLUS_10REAL/1_SIM/SIMSDSSREAL_4D_BS20/PIP_PLUS_10REAL_SIMSDSSREAL_4D_BS20-0008
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/PLUS_10REAL/1_SIM/SIMSDSSREAL_4D_BS20/PIP_PLUS_10REAL_SIMSDSSREAL_4D_BS20-0009
  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/PLUS_10REAL/1_SIM/SIMSDSSREAL_4D_BS20/PIP_PLUS_10REAL_SIMSDSSREAL_4D_BS20-0010
